### ISSUE TITLE
ConfigAttributeError on fresh install

### ISSUE THREAD

**Issue by AkshatM** [pwenker/chessli#23]
Encountered the following issue when downloading and installing for the first time:

```
❯ chessli --help
Traceback (most recent call last):
  File "/home/akshat/.pyenv/versions/3.8.6/bin/chessli", line 5, in <module>
    from chessli.cli.main import app
  File "/home/akshat/.pyenv/versions/3.8.6/lib/python3.8/site-packages/chessli/__init__.py", line 137, in <module>
    berserk_client = get_berserk_client(main_config.token)
  File "/home/akshat/.pyenv/versions/3.8.6/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 353, in __getattr__
    self._format_and_raise(
  File "/home/akshat/.pyenv/versions/3.8.6/lib/python3.8/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/akshat/.pyenv/versions/3.8.6/lib/python3.8/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/akshat/.pyenv/versions/3.8.6/lib/python3.8/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/akshat/.pyenv/versions/3.8.6/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/akshat/.pyenv/versions/3.8.6/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/home/akshat/.pyenv/versions/3.8.6/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 470, in _get_node
    raise ConfigKeyError(f"Missing key {key}")
omegaconf.errors.ConfigAttributeError: Missing key token
    full_key: token
    object_type=dict
```

Environment: Ubuntu 18.0.4, System76 Laptop, Python 3.8

I imagine there's a config file I have to supply somewhere, but this doesn't seem to be reflected in the docs?

**Comment by BlackBlack667** [comment]
Same for me.

Environment: Fedora Silverblue, Python 3.9 and Python 3.8 on Conda.

**Comment by faculb** [comment]
I have the same problem

**Comment by pwenker** [comment]
Sorry for the late response! 
Does this part in the documentation solve the issue? 
https://pwenker.com/chessli/tutorial/how_to_set_up_chessli/

**Comment by BlackBlack667** [comment]
No. Chessli crashes same error regardless of arguments provided.

**Comment by pwenker** [comment]
@BlackBlack667: 

I don't exactly what you mean with "regardless of arguments provided". The link I provided goes through some additional setup steps needed. 
One of them is the creation of an API acces token: 

https://pwenker.com/chessli/tutorial/how_to_set_up_chessli/#lichess-api-authentification

It's been a while that I worked on the code, but from the error message in the initial issue entry, I guess that is the one step missing :)

**Comment by BlackBlack667** [comment]
Changed config and it works now!

**Comment by pwenker** [comment]
Awesome! 
Thank you three for your feedback!
I close this issue and will place some notes into the documentation to make these necessary configuration setup-steps more visible. 
Feel free to reopen if anything is not solved yet or open new issues if other problems come up :)
