### ISSUE TITLE
Charmap cannot encode characters found in certain games

### ISSUE THREAD

**Issue by Epic-Doughnut** [pwenker/chessli#8]
I got the following error after running `chessli games fetch`:

```Traceback (most recent call last):
  File "C:\Python39\Scripts\chessli-script.py", line 33, in <module>
    sys.exit(load_entry_point('chessli', 'console_scripts', 'chessli')())
  File "c:\python39\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python39\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "c:\users\joeys\chessli\chessli\cli\games.py", line 58, in fetch
    game_manager.fetch_games()
  File "c:\users\joeys\chessli\chessli\games.py", line 105, in fetch_games
    chessli_game.store()
  File "c:\users\joeys\chessli\chessli\games.py", line 167, in store
    (self.path / self.name).with_suffix(".pgn").write_text(str(self.pgn))
  File "c:\python39\lib\pathlib.py", line 1275, in write_text
    return f.write(data)
  File "c:\python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 695: character maps to <undefined>
```

'\u2192' is “→”, and I'm not sure exactly where in lichess this symbol would be found, but it occurred when trying to import this game: https://lichess.org/r0crIC7x/black

**Comment by Epic-Doughnut** [comment]
I was able to fix it by modifying the line in games.py to `(self.path / self.name).with_suffix(".pgn").write_text(str(self.pgn), encoding="utf_8")`

**Comment by pwenker** [comment]
Thanks for reporting the error and especially for providing a simple fix! 
I'm currently working on v0.2 and will make sure apply a fix for that problem there!

**Comment by pwenker** [comment]
This is fixed now in the `main branch` and will be part of `v0.2`, Thanks again :)
